name: Run pre-commit

run-name: ${{ github.workflow }} for ${{ github.ref_name }}

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run pre-commit
        uses: zeevro/action-pre-commit-uv@main # TODO: Replace with tox-dev/action-pre-commit-uv once PR is merged
